# chain = "mumbai"
chain = "mainnet"
datadir = "/var/lib/bor/data"
syncmode = "full"

[telemetry]
metrics = true
prometheus-addr = "127.0.0.1:7071"

[miner]
# *** Validator params
# *** Uncomment and configure the following lines in case you run a validator.
# mine = true
# etherbase = "VALIDATOR ADDRESS"
gasprice = "30000000000"
gasceil = 20000000


[txpool]
accountqueue = 16
accountslots = 16
globalqueue = 32768
globalslots = 32768
lifetime = "1h30m0s"
nolocals = true
pricelimit = 30000000000

[p2p]
# *** Validator params
# *** Uncomment and configure the following lines in case you run a validator.
# nodiscover = true
# maxpeers = 1
  [p2p.discovery]
  bootnodes = ["enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303", "enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"]

# *** Validator params
# *** Uncomment and configure the following lines in case you run a validator.

# keystore = "/var/lib/bor/keystore"

# [accounts]
# allow-insecure-unlock = true
# password = "/var/lib/bor/password.txt"
# unlock = ["VALIDATOR ADDRESS"]